-- ==============================================================================
-- SKEMA DATABASE SUPABASE & REALTIME - PUSKESMAS KUALA CENAKU (VERSI TERBARU)
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> Run
-- ==============================================================================

-- 1. TABEL ANTREAN UTAMA
CREATE TABLE IF NOT EXISTS public.antrean (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor TEXT NOT NULL,
    nama TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'MENUNGGU', -- MENUNGGU | MEMANGGIL | TERLAMBAT | SELESAI
    estimasi_menit INTEGER NOT NULL DEFAULT 5,
    urutan INTEGER NOT NULL DEFAULT 0,
    panggilan_ke INTEGER NOT NULL DEFAULT 0,
    last_called_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    durasi_aktual_menit NUMERIC,
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migrasi aman untuk menambahkan kolom baru jika tabel sudah ada sebelumnya
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='antrean' AND column_name='urutan') THEN
        ALTER TABLE public.antrean ADD COLUMN urutan INTEGER NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='antrean' AND column_name='panggilan_ke') THEN
        ALTER TABLE public.antrean ADD COLUMN panggilan_ke INTEGER NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='antrean' AND column_name='last_called_at') THEN
        ALTER TABLE public.antrean ADD COLUMN last_called_at TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='antrean' AND column_name='finished_at') THEN
        ALTER TABLE public.antrean ADD COLUMN finished_at TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='antrean' AND column_name='durasi_aktual_menit') THEN
        ALTER TABLE public.antrean ADD COLUMN durasi_aktual_menit NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='antrean' AND column_name='is_archived') THEN
        ALTER TABLE public.antrean ADD COLUMN is_archived BOOLEAN NOT NULL DEFAULT false;
    END IF;
END $$;

-- Index untuk mempercepat filter dan pengurutan
CREATE INDEX IF NOT EXISTS idx_antrean_status ON public.antrean(status);
CREATE INDEX IF NOT EXISTS idx_antrean_urutan ON public.antrean(urutan ASC, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_antrean_archived ON public.antrean(is_archived);
CREATE INDEX IF NOT EXISTS idx_antrean_created_at ON public.antrean(created_at DESC);

-- 2. TABEL PENGATURAN, KOORDINAT & PENGUMUMAN DARURAT
CREATE TABLE IF NOT EXISTS public.pengaturan (
    id TEXT PRIMARY KEY DEFAULT 'puskesmas_config',
    nama_puskesmas TEXT DEFAULT 'Puskesmas Kuala Cenaku',
    alamat_puskesmas TEXT DEFAULT 'Jl. Kesehatan No. 1, Kuala Cenaku, Kab. Indragiri Hulu, Riau',
    logo_url TEXT DEFAULT '🏥',
    foto_puskesmas_url TEXT DEFAULT 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=1200&auto=format&fit=crop&q=80',
    info_penting TEXT DEFAULT 'Wajib membawa KTP atau Kartu Keluarga (KK) fisik saat datang ke loket. Toleransi keterlambatan maksimal 15 Menit.',
    status_buka BOOLEAN DEFAULT TRUE,
    pengumuman_darurat TEXT DEFAULT '',
    maps_url TEXT DEFAULT 'https://maps.google.com/?q=-0.5282,102.5853',
    latitude NUMERIC DEFAULT -0.5282,
    longitude NUMERIC DEFAULT 102.5853,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migrasi aman untuk tabel pengaturan jika kolom koordinat/maps_url belum ada
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='pengaturan' AND column_name='maps_url') THEN
        ALTER TABLE public.pengaturan ADD COLUMN maps_url TEXT DEFAULT 'https://maps.google.com/?q=-0.5282,102.5853';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='pengaturan' AND column_name='latitude') THEN
        ALTER TABLE public.pengaturan ADD COLUMN latitude NUMERIC DEFAULT -0.5282;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='pengaturan' AND column_name='longitude') THEN
        ALTER TABLE public.pengaturan ADD COLUMN longitude NUMERIC DEFAULT 102.5853;
    END IF;
END $$;

-- Inisialisasi baris konfigurasi default
INSERT INTO public.pengaturan (
    id, 
    nama_puskesmas, 
    alamat_puskesmas, 
    logo_url, 
    foto_puskesmas_url, 
    info_penting, 
    status_buka, 
    pengumuman_darurat,
    maps_url,
    latitude,
    longitude
) VALUES (
    'puskesmas_config',
    'Puskesmas Kuala Cenaku',
    'Jl. Kesehatan No. 1, Kuala Cenaku, Kab. Indragiri Hulu, Riau',
    '🏥',
    'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=1200&auto=format&fit=crop&q=80',
    'Wajib membawa KTP atau Kartu Keluarga (KK) fisik saat datang ke loket. Toleransi keterlambatan maksimal 15 Menit.',
    TRUE,
    '',
    'https://maps.google.com/?q=-0.5282,102.5853',
    -0.5282,
    102.5853
) ON CONFLICT (id) DO UPDATE SET
    latitude = COALESCE(public.pengaturan.latitude, -0.5282),
    longitude = COALESCE(public.pengaturan.longitude, 102.5853);

-- 3. AKTIFKAN SUPABASE REALTIME REPLICATION
ALTER PUBLICATION supabase_realtime ADD TABLE public.antrean;
ALTER PUBLICATION supabase_realtime ADD TABLE public.pengaturan;

-- 4. KEAMANAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.antrean ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengaturan ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses Publik untuk Tabel antrean
DROP POLICY IF EXISTS "Izinkan Baca Publik Antrean" ON public.antrean;
CREATE POLICY "Izinkan Baca Publik Antrean" ON public.antrean FOR SELECT USING (true);

DROP POLICY IF EXISTS "Izinkan Tambah Antrean Mandiri" ON public.antrean;
CREATE POLICY "Izinkan Tambah Antrean Mandiri" ON public.antrean FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Izinkan Update Status Antrean" ON public.antrean;
CREATE POLICY "Izinkan Update Status Antrean" ON public.antrean FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Izinkan Hapus/Batal Antrean" ON public.antrean;
CREATE POLICY "Izinkan Hapus/Batal Antrean" ON public.antrean FOR DELETE USING (true);

-- Kebijakan Akses Publik untuk Tabel pengaturan
DROP POLICY IF EXISTS "Izinkan Baca Pengaturan Publik" ON public.pengaturan;
CREATE POLICY "Izinkan Baca Pengaturan Publik" ON public.pengaturan FOR SELECT USING (true);

DROP POLICY IF EXISTS "Izinkan Update Pengaturan" ON public.pengaturan;
CREATE POLICY "Izinkan Update Pengaturan" ON public.pengaturan FOR ALL USING (true);
